spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 232352942341-cmvf9ht6cis6unbvo35ia40cg4dlsmsj.apps.googleusercontent.com
            client-secret: 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
            scope:
            - profile
            - email
